development:
  access_key_id: AKIAJTH75B2LOXGRGTLA
  secret_access_key: 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

production:
  access_key_id: AKIAJTH75B2LOXGRGTLA
  secret_access_key: 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